services:

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 20s
      timeout: 10s
      retries: 3
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - softroute-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      - softroute-network

  config-service:
    build: ./config-service
    container_name: config-service
    restart: always
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/healthy/default" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - softroute-network
    environment:
      GIT_REPOSITORY_URL: ${GIT_REPOSITORY_URL}
      GIT_USER: ${GIT_USER}
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      GIT_BRANCH: {GIT_BRANCH}


volumes:
  mysql-data:


networks:
  softroute-network:
    driver: bridge
