services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - softroute-network

  iam-service:
    build: ./iam-service
    container_name: iam-service
    restart: always
    depends_on:
      - api-gateway
    networks:
      - softroute-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    environment:
      MAIL_USERNAME: YOUR_USERNAME
      MAIL_PASSWORD: YOUR_PASSWORD
    depends_on:
      - iot-device-service
    networks:
      - softroute-network

  iot-device-service:
    build: ./iot-device-service
    container_name: iot-device-service
    restart: always
    depends_on:
      - iam-service
    networks:
      - softroute-network

  organization-service:
    build: ./organization-service
    container_name: organization-service
    restart: always
    depends_on:
      - iam-service
    networks:
      - softroute-network

  package-service:
    build: ./package-service
    container_name: package-service
    restart: always
    environment:
      GOOGLE_MAPS_API_KEY: YOUR-API-KEY
    depends_on:
      - iam-service
    networks:
      - softroute-network

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 20s
      timeout: 10s
      retries: 3
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - softroute-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      - softroute-network

  config-service:
    build: ./config-service
    container_name: config-service
    restart: always
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/healthy/default" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - softroute-network
    environment:
      GIT_REPOSITORY_URL: ${GIT_REPOSITORY_URL}
      GIT_USER: ${GIT_USER}
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      GIT_BRANCH: ${GIT_BRANCH}


volumes:
  mysql-data:
  rabbitmq-data:

networks:
  softroute-network:
    driver: bridge
