services:

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 20s
      timeout: 10s
      retries: 3
    networks:
      - sofroute-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      - sofroute-network


volumes:
  mysql-data:


networks:
  sofroute-network:
    driver: bridge
