server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: iam-route
          uri: lb://IAM-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: package-route
          uri: lb://PACKAGE-SERVICE
          predicates:
            - Path=/api/v1/packages/**, /api/v1/shipments/**, /ws/**
          filters:
            - AuthenticationFilter
        - id: organization-service
          uri: lb://ORGANIZATION-SERVICE
          predicates:
            - Path=/api/v1/clients/**, /api/v1/employees
          filters:
            - AuthenticationFilter
        - id: iot-device-service
          uri: lb://IOT-DEVICE-SERVICE
          predicates:
            - Path=/api/v1/iot-devices/**
        - id: notification-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - POST
              - GET
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true


eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka