server:
    port: 8081
spring:
    application:
        name: tracking-service
    datasource:
        url: ${DATABASE_CONECTION_STRING}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    flyway:
        default-schema: ${FLYWAY_SCHEMA}
        enabled: true
        locations: classpath:db/migration/structure, classpath:db/migration/data
        validate-on-migrate: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    rabbitmq:
        host: ${RABBITMQ_HOST}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}
        port: ${RABBITMQ_PORT}
