server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: tracking-service
  datasource:
    url: jdbc:mysql://localhost:3306/trackingdb
    username: root
    password: 123456
  flyway:
    default-schema: trackingdb
    enabled: true
    locations: classpath:db/migration/structure, classpath:db/migration/data
    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5674

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

google:
  maps:
    api:
      key: SECRET_API_KEY