server:
    port: 8082
spring:
    application:
        name: iot-device-service
    datasource:
        password: 123456
        url: jdbc:mysql://localhost:3306/devices
        username: root
    jpa:
        hibernate:
            ddl-auto: update
    rabbitmq:
        host: localhost
        password: guest
        username: guest
        virtual-host: /
        port: 5674
