server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: iot-device-service
  datasource:
    url: jdbc:mysql://localhost:3306/iotdevicedb
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5674

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true