spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:mysql://localhost:3306/organizationdb
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    default-schema: organizationdb
    enabled: true
    locations: classpath:db/migration/structure, classpath:db/migration/data
    validate-on-migrate: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true


server:
  port: 8083
