server:
    port: 8888

spring:
    application:
        name: config-service
    cloud:
        config:
            server:
                git:
                    uri: ${GIT_REPOSITORY_URL}
                    default-label: ${GIT_BRANCH}
                    username: ${GIT_USER}
                    password: ${GIT_ACCESS_TOKEN}